apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: downkit
spec:
  rules:
    - host: downkit.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: downkit
                port:
                  number: 80



