apiVersion: v1
kind: Service
metadata:
  name: downkit
  labels:
    app: downkit
spec:
  selector:
    app: downkit
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP



